name = "custom-mc-mezo-org-zaraz-segment"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "26fce33e6ba0b1df3188fb3ae581e5c5"

[[kv_namespaces]]
binding = "KV"
id = "d2633c5d30ff4ce1aa771efbce80f6b4"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true

[observability.traces]
enabled = true
